/*
 * Transport Operator MaaS Provider API
 * An API between MaaS providers and transport operators for booking trips and corresponding assets. <p>The documentation (examples, process flows and sequence diagrams) can be found at <a href=\"https://github.com/TOMP-WG/TOMP-API/\">github</a>.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client

/**
 * API response returned by API call.
 *
 * @param <T> The type of data that is deserialized from response body
</T> */
class ApiResponse<T> @JvmOverloads constructor(val statusCode: Int, val headers: Map<String, List<String>>, data: T? = null) {
    val data: T
    /**
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     * @param data The object deserialized from response bod
     */
    /**
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     */
    init {
        this.data = data
    }
}
