/*
 * Transport Operator MaaS Provider API
 * An API between MaaS providers and transport operators for booking trips and corresponding assets. <p>The documentation (examples, process flows and sequence diagrams) can be found at <a href=\"https://github.com/TOMP-WG/TOMP-API/\">github</a>.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client

import javax.annotation.Generated

@Generated(value = ["io.swagger.codegen.v3.generators.java.JavaClientCodegen"], date = "2020-03-24T12:09:05.155Z[GMT]")
class Pair(name: String, value: String?) {
    var name = ""
        private set(name) {
            if (!isValidString(name)) return
            field = name
        }
    var value: String? = ""
        private set(value) {
            if (!isValidString(value)) return
            field = value
        }

    init {
        this.name = name
        this.value = value
    }

    private fun isValidString(arg: String?): Boolean {
        if (arg == null) return false
        return if (arg.trim { it <= ' ' }.isEmpty()) false else true
    }
}
